name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build-functions:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./functions
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: functions
          path: ./functions/lib
  build-frontend:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: frontend
          path: ./frontend/build
  deploy:
    name: Deploy
    needs: [build-frontend, build-functions]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./functions
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Functions Artifact
        uses: actions/download-artifact@master
        with:
          name: functions
          path: ./functions/lib
      - name: Download Frontend Artifact
        uses: actions/download-artifact@master
        with:
          name: frontend
          path: ./frontend/build
      - name: Install Dependencies
        run: npm install
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions,hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}